Repository codesquad-members-2025/be-chess, pull requests merged in 2025-03, with the labels that each got.

#1 [Glad] step-2 체스
  .gitattributes
  .gitignore
  README.md
  app/build.gradle
  app/src/main/java/org/chess/App.java
  app/src/main/java/org/chess/domain/piece/Pawn.java
  app/src/test/java/org/chess/AppTest.java
  app/src/test/java/org/chess/domain/piece/PawnTest.java
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Step2-1

#2 [빙빙] step-2 1단계: 체스 프로젝트 시작
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#7 [디노] step-2 1단계: 체스 프로젝트 시작
  .gitignore
  .idea/.gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/chess/Pawn.java
  src/test/java/org/chess/PawnTest.java
Labels: Step2-1

#6 [배찌] step-1 체스 프로젝트 시작
  .gitattributes
  .gitignore
  app/build.gradle
  app/src/main/java/chess/Pawn.java
  app/src/test/java/chess/PawnTest.java
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Step2-1

#8 [MUD] step2-1 체스 프로젝트 시작
  .gitattributes
  .gitignore
  app/build.gradle
  app/src/main/java/Main.java
  app/src/main/java/Pawn.java
  app/src/test/java/PawnTest.java
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Step2-1

#10 [빙빙] step-2 2단계: 체스판 생성
  README.md
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-2

#11 [Glad] Step 2-2 체스 체스판 만들기
  README.md
  app/src/main/java/org/chess/domain/board/Board.java
  app/src/main/java/org/chess/domain/piece/Pawn.java
  app/src/main/java/org/chess/domain/pieces/Pawn.java
  app/src/test/java/org/chess/domain/board/BoardTest.java
  app/src/test/java/org/chess/domain/piece/PawnTest.java
  app/src/test/java/org/chess/domain/pieces/PawnTest.java
Labels: Step2-2

#13 [케이딘] step-2 1단계: 체스 프로젝트 시작
  build.gradle
  setting.gradle
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#14 [훈] step-2.1 체스 프로젝트 시작
  .gitattributes
  .gitignore
  app/build.gradle
  app/src/main/java/org/example/Pawn.java
  app/src/test/java/org/example/PawnTest.java
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Step2-1

#12 [배찌] step2 체스판 생성
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/Pawn.java
  app/src/main/java/pieces/Pawn.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/pieces/PawnTest.java
Labels: Step2-2

#16 [디노] step-2 2단계: 체스판 생성
  README.md
  src/main/java/org/chess/Board.java
  src/main/java/org/chess/Pawn.java
  src/main/java/org/pieces/Pawn.java
  src/test/java/org/chess/BoardTest.java
  src/test/java/org/chess/PawnTest.java
  src/test/java/org/pieces/PawnTest.java
Labels: Step2-2

#18 [빙빙] step2 3단계: 체스판 초기화
  README.md
  src/main/java/chess/Application.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-3

#19 [Glad] Step 2-3 체스판 초기화
  README.md
  app/src/main/java/org/chess/App.java
  app/src/main/java/org/chess/console/Input.java
  app/src/main/java/org/chess/domain/board/Board.java
  app/src/main/java/org/chess/domain/pieces/Pawn.java
  app/src/test/java/org/chess/domain/board/BoardTest.java
  app/src/test/java/org/chess/domain/pieces/PawnTest.java
Labels: Step2-3

#20 [지토] step-1 Pawn 클래스 구현
  chess/.gitignore
  chess/.idea/.gitignore
  chess/.idea/gradle.xml
  chess/.idea/misc.xml
  chess/.idea/vcs.xml
  chess/build.gradle
  chess/gradle/wrapper/gradle-wrapper.jar
  chess/gradle/wrapper/gradle-wrapper.properties
  chess/gradlew
  chess/gradlew.bat
  chess/settings.gradle
  chess/src/main/java/org/example/Main.java
  chess/src/main/java/org/example/Pawn.java
  chess/src/test/java/PawnTest.java
Labels: Step2-1

#9 [BRIE] step2-1 체스 프로젝트 시작
  .gitattributes
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/java/Pawn.java
  app/src/test/java/PawnTest.java
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Step2-1

#21 [배찌] step3 체스판 초기화
  app/src/main/java/App.java
  app/src/main/java/chess/Board.java
  app/src/main/java/pieces/Pawn.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/pieces/PawnTest.java
Labels: Step2-3

#24 [훈] step2-2 체스판 생성
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/java/org/chess/Board.java
  app/src/main/java/org/chess/pieces/Pawn.java
  app/src/main/java/org/example/Pawn.java
  app/src/test/java/org/chess/BoardTest.java
  app/src/test/java/org/chess/pieces/PawnTest.java
  app/src/test/java/org/example/PawnTest.java
Labels: Step2-2

#25 [MUD] step-2 체스판 생성
  app/build.gradle
  app/src/main/java/Pawn.java
  app/src/main/java/chess/Board.java
  app/src/main/java/pieces/Pawn.java
  app/src/test/java/PawnTest.java
  app/src/test/java/Pieces/PawnTest.java
  app/src/test/java/chess/BoardTest.java
Labels: Step2-2

#22 [디노] step-2 3단계: 체스판 초기화
  README.md
  src/main/java/org/chess/Board.java
  src/main/java/org/chess/PlayGame.java
  src/main/java/org/pieces/Pawn.java
  src/test/java/org/chess/BoardTest.java
  src/test/java/org/pieces/PawnTest.java
Labels: Step2-3

#23 [JOHNNIE] 2단계: 체스판 생성
  .gitignore
  src/main/java/chess/Board.java
  src/main/java/chess/piece/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/piece/PawnTest.java
Labels: Step2-2

#27 [케이딘] step-2 2단계: 체스판 생성
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Board.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/test/java/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step2-2

#28 [빙빙] step-2 4단계: 모든 기물 배치하기
  README.md
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step2-4

#30 [지토] step2-1 체스판 생성
  chess/.idea/gradle.xml
  chess/build.gradle
  chess/src/main/java/org/example/Pawn.java
  chess/src/test/java/PawnTest.java
Labels: Step2-1

#31 [JOHNNIE] 3단계 체스판 초기화
  .gitattributes
  .gitignore
  .gradle/8.10/checksums/checksums.lock
  .gradle/8.10/executionHistory/executionHistory-DESKTOP-27SP56P.lock
  .gradle/8.10/executionHistory/executionHistory.bin
  .gradle/8.10/executionHistory/executionHistory.lock
  .gradle/8.10/fileHashes/fileHashes-DESKTOP-27SP56P.lock
  .gradle/8.10/fileHashes/fileHashes.bin
  .gradle/8.10/fileHashes/fileHashes.lock
  .gradle/8.10/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup-DESKTOP-27SP56P.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system-DESKTOP-27SP56P.probe
  .gradle/file-system.probe
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/workspace-DESKTOP-27SP56P.xml
  .idea/workspace.xml
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/chess/ChessGame.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/piece/Pawn.java
  src/main/java/chess/piece/Piece.java
  src/test/java/chess/piece/PawnTest.java
  src/test/java/chess/piece/board/BoardTest.java
Labels: Step2-3

#32 [배찌] step4 모든 기물 배치하기
  app/src/main/java/App.java
  app/src/main/java/chess/Board.java
  app/src/main/java/pieces/Pawn.java
  app/src/main/java/pieces/Piece.java
  app/src/main/java/utils/StringUtils.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/pieces/PawnTest.java
  app/src/test/java/pieces/PieceTest.java
  app/src/test/java/utils/StringUtilsTest.java
Labels: Step2-4

#33 [Glad] Step 2- 4 체스 모든 기물 배치하기
  README.md
  app/src/main/java/org/chess/domain/board/Board.java
  app/src/main/java/org/chess/domain/pieces/Pawn.java
  app/src/main/java/org/chess/domain/pieces/Piece.java
  app/src/main/java/org/chess/utils/StringUtils.java
  app/src/test/java/org/chess/AppTest.java
  app/src/test/java/org/chess/domain/board/BoardTest.java
  app/src/test/java/org/chess/domain/pieces/PawnTest.java
  app/src/test/java/org/chess/domain/pieces/PieceTest.java
  app/src/test/java/org/chess/utils/StringUtilsTest.java
Labels: Step2-4

#34 [훈] step2-3 체스판 초기화
  README.md
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/Chess.java
  app/src/main/java/chess/pieces/Pawn.java
  app/src/main/java/org/chess/Board.java
  app/src/main/java/org/chess/pieces/Pawn.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/chess/pieces/PawnTest.java
  app/src/test/java/org/chess/BoardTest.java
  app/src/test/java/org/chess/pieces/PawnTest.java
Labels: Step2-3

#35 [디노] step-2 4단계: 모든 기물 배치하기
  README.md
  src/main/java/org/chess/Board.java
  src/main/java/org/chess/PlayGame.java
  src/main/java/org/pieces/Pawn.java
  src/main/java/org/pieces/Piece.java
  src/main/java/org/utils/StringUtils.java
  src/test/java/org/chess/BoardTest.java
  src/test/java/org/pieces/PawnTest.java
  src/test/java/org/pieces/PieceTest.java
Labels: Step2-4

#40 [케이딘] step2 3단계: 체스판 초기화
  src/main/java/Application.java
  src/main/java/Board.java
  src/main/java/pieces/Pawn.java
  src/test/java/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step2-3

#41 [지토] step-2 체스판 생성
  chess/build.gradle
  chess/src/main/java/chess/Board.java
  chess/src/main/java/chess/Main.java
  chess/src/main/java/chess/Pawn.java
  chess/src/test/java/PawnTest.java
  chess/src/test/java/pieces/BoardTest.java
  chess/src/test/java/pieces/PawnTest.java
Labels: Step2-2

#43 [BRIE] step2-3 체스판 초기화
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/ChessGame.java
  app/src/main/java/pieces/Pawn.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/pieces/PawnTest.java
Labels: Step2-3

#45 [디노] step-2 5단계: 기물 위치 부여 및 점수계산
  README.md
  src/main/java/org/chess/Board.java
  src/main/java/org/chess/Coordinate.java
  src/main/java/org/chess/Rank.java
  src/main/java/org/pieces/Piece.java
  src/test/java/org/chess/BoardTest.java
  src/test/java/org/pieces/PieceTest.java
Labels: Step2-5

#46 [빙빙] step2 5단계: 기물 위치 부여 및 점수계산
  README.md
  src/main/java/chess/Board.java
  src/main/java/chess/Position.java
  src/main/java/chess/Rank.java
  src/main/java/chess/pieces/Piece.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step2-5

#47 [배찌] step5 기물 위치 부여 및 점수계산
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/Rank.java
  app/src/main/java/pieces/Piece.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/pieces/PieceTest.java
Labels: Step2-5

#48 [훈] step2-4 기물 위치 부여 및 점수계산
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/pieces/Pawn.java
  app/src/main/java/chess/pieces/Piece.java
  app/src/main/java/chess/utils/StringUtils.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/chess/pieces/PawnTest.java
  app/src/test/java/chess/pieces/PieceTest.java
Labels: Step2-4

#50 [BRIE] step2-4 모든 기물 배치하기
  app/src/main/java/chess/Board.java
  app/src/main/java/pieces/Pawn.java
  app/src/main/java/pieces/Piece.java
  app/src/main/java/utils/StringUtils.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/pieces/PawnTest.java
  app/src/test/java/pieces/PieceTest.java
Labels: Step2-4

#52 [지토] step-3 체스판 초기화
  chess/src/main/java/chess/Board.java
  chess/src/main/java/chess/Main.java
  chess/src/main/java/chess/Pawn.java
  chess/src/test/java/pieces/BoardTest.java
  chess/src/test/java/pieces/PawnTest.java
Labels: Step2-3

#54 [Glad] Step 2 - 5 기물 위치 부여 및 점수계산
  README.md
  app/src/main/java/org/chess/domain/board/Board.java
  app/src/main/java/org/chess/domain/board/Position.java
  app/src/main/java/org/chess/domain/board/Rank.java
  app/src/main/java/org/chess/domain/pieces/Piece.java
  app/src/test/java/org/chess/domain/board/BoardTest.java
  app/src/test/java/org/chess/domain/board/PositionTest.java
  app/src/test/java/org/chess/domain/board/RankTest.java
  app/src/test/java/org/chess/domain/pieces/PieceTest.java
Labels: Step2-5

#58 [Elbin] step-3 3단계: 체스판 초기화
  app/build.gradle
  app/src/main/java/ChessGame.java
  app/src/main/java/chess/Board.java
  app/src/main/java/pieces/Pawn.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/pieces/PawnTest.java
Labels: Step2-3

#60 [빙빙] step2 6단계 - 기물 이동 구현
  README.md
  src/main/java/chess/Application.java
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/ChessView.java
  src/main/java/chess/Direction.java
  src/main/java/chess/Position.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/TestUtil.java
  src/test/java/chess/pieces/BishopTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/KnightTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/QueenTest.java
  src/test/java/chess/pieces/RookTest.java
Labels: Step2-6

#61 [디노] step-2 6단계 - 기물 이동 구현
  .gitignore
  README.md
  src/main/java/org/chess/Board.java
  src/main/java/org/chess/ChessView.java
  src/main/java/org/chess/Coordinate.java
  src/main/java/org/chess/Game.java
  src/main/java/org/chess/PlayGame.java
  src/main/java/org/pieces/Bishop.java
  src/main/java/org/pieces/Blank.java
  src/main/java/org/pieces/King.java
  src/main/java/org/pieces/Knight.java
  src/main/java/org/pieces/Pawn.java
  src/main/java/org/pieces/Piece.java
  src/main/java/org/pieces/Queen.java
  src/main/java/org/pieces/Rook.java
  src/test/java/org/chess/BoardTest.java
  src/test/java/org/pieces/BishopTest.java
  src/test/java/org/pieces/KingTest.java
  src/test/java/org/pieces/KnightTest.java
  src/test/java/org/pieces/PawnTest.java
  src/test/java/org/pieces/PieceTest.java
  src/test/java/org/pieces/QueenTest.java
  src/test/java/org/pieces/RookTest.java
Labels: Step2-6

#62 [Glad] Step 2 - 6 기물 이동 구현
  README.md
  app/src/main/java/org/chess/App.java
  app/src/main/java/org/chess/console/Input.java
  app/src/main/java/org/chess/domain/board/Board.java
  app/src/main/java/org/chess/domain/board/Position.java
  app/src/main/java/org/chess/domain/board/Rank.java
  app/src/main/java/org/chess/domain/game/Game.java
  app/src/main/java/org/chess/domain/piece/Color.java
  app/src/main/java/org/chess/domain/piece/Piece.java
  app/src/main/java/org/chess/domain/piece/PieceFactory.java
  app/src/main/java/org/chess/domain/piece/impl/Bishop.java
  app/src/main/java/org/chess/domain/piece/impl/Blank.java
  app/src/main/java/org/chess/domain/piece/impl/King.java
  app/src/main/java/org/chess/domain/piece/impl/Knight.java
  app/src/main/java/org/chess/domain/piece/impl/Pawn.java
  app/src/main/java/org/chess/domain/piece/impl/Queen.java
  app/src/main/java/org/chess/domain/piece/impl/Rook.java
  app/src/main/java/org/chess/domain/pieces/Piece.java
  app/src/main/java/org/chess/utils/StringUtils.java
  app/src/test/java/org/chess/domain/board/BoardTest.java
  app/src/test/java/org/chess/domain/board/PositionTest.java
  app/src/test/java/org/chess/domain/board/RankTest.java
  app/src/test/java/org/chess/domain/piece/PieceFactoryTest.java
  app/src/test/java/org/chess/domain/piece/impl/BishopTest.java
  app/src/test/java/org/chess/domain/piece/impl/BlankTest.java
  app/src/test/java/org/chess/domain/piece/impl/KingTest.java
  app/src/test/java/org/chess/domain/piece/impl/KnightTest.java
  app/src/test/java/org/chess/domain/piece/impl/PawnTest.java
  app/src/test/java/org/chess/domain/piece/impl/QueenTest.java
  app/src/test/java/org/chess/domain/piece/impl/RookTest.java
  app/src/test/java/org/chess/domain/piece/provider/TestBoardProvider.java
  app/src/test/java/org/chess/domain/pieces/PieceTest.java
  app/src/test/java/org/chess/utils/StringUtilsTest.java
Labels: Step2-6, Step2-7

#64 [MUD] step4 모든 기물 배치하기
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/ChessGame.java
  app/src/main/java/pieces/Pawn.java
  app/src/main/java/pieces/Piece.java
  app/src/main/java/utils/StringUtils.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/pieces/PawnTest.java
  app/src/test/java/pieces/PieceTest.java
Labels: Step2-4

#65 [훈] step2-5 기물 위치 부여 및 점수계산
  .gitignore
  .idea/gradle.xml
  .idea/uiDesigner.xml
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/Chess.java
  app/src/main/java/chess/Position.java
  app/src/main/java/chess/Rank.java
  app/src/main/java/chess/pieces/Piece.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/chess/pieces/PieceTest.java
Labels: Step2-5

#66 [디노] step-2 7단계: 예외 처리
  README.md
  src/main/java/org/chess/ChessView.java
  src/main/java/org/chess/Coordinate.java
  src/main/java/org/chess/Game.java
  src/main/java/org/chess/PlayGame.java
  src/main/java/org/pieces/Bishop.java
  src/main/java/org/pieces/Blank.java
  src/main/java/org/pieces/King.java
  src/main/java/org/pieces/Knight.java
  src/main/java/org/pieces/Piece.java
  src/main/java/org/pieces/Queen.java
  src/main/java/org/pieces/Rook.java
  src/test/java/org/chess/BoardTest.java
  src/test/java/org/chess/CoordinateTest.java
Labels: Step2-7

#67 [빙빙] step2 7단계: 예외 처리
  README.md
  src/main/java/chess/Application.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/Position.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/GameTest.java
  src/test/java/chess/TestUtil.java
  src/test/java/chess/pieces/KnightTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/QueenTest.java
Labels: Step2-7

#68 [JOHNNIE] 7단계: 예외 처리
  src/main/java/chess/ChessGame.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/game/Game.java
  src/main/java/chess/piece/Bishop.java
  src/main/java/chess/piece/King.java
  src/main/java/chess/piece/Pawn.java
  src/main/java/chess/piece/Queen.java
  src/main/java/chess/piece/Rook.java
  src/main/java/chess/util/BoardPositionValidator.java
  src/main/java/chess/view/ChessView.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/game/GameTest.java
  src/test/java/chess/piece/QueenTest.java
  src/test/java/chess/view/ViewTest.java
Labels: Step2-7

#69 [BRIE] Step2-5 기물 위치 부여 및 점수계산
  .gitignore
  README.md
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/BoardView.java
  app/src/main/java/chess/ChessGame.java
  app/src/main/java/chess/Position.java
  app/src/main/java/chess/Rank.java
  app/src/main/java/chess/ScoreCalculator.java
  app/src/main/java/pieces/Piece.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/chess/BoardViewTest.java
  app/src/test/java/chess/ScoreCalculatorTest.java
  app/src/test/java/pieces/PieceTest.java
Labels: Step2-5

#70 [지토] step-4 모든 기물 배치하기
  chess/src/main/java/chess/Board.java
  chess/src/main/java/chess/Color.java
  chess/src/main/java/chess/Main.java
  chess/src/main/java/chess/Pawn.java
  chess/src/main/java/chess/Piece.java
  chess/src/main/java/chess/Type.java
  chess/src/main/java/utils/StringUtils.java
  chess/src/test/java/pieces/BoardTest.java
  chess/src/test/java/pieces/PawnTest.java
  chess/src/test/java/pieces/PieceTest.java
Labels: Step2-4

#71 [Elbin] step-4 4단계: 모든 기물 배치하기
  .idea/encodings.xml
  .idea/uiDesigner.xml
  app/build.gradle
  app/src/main/java/ChessGame.java
  app/src/main/java/chess/Board.java
  app/src/main/java/pieces/Piece.java
  app/src/main/java/utils/StringUtils.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/pieces/PieceTest.java
Labels: Step2-4

#72 [Kaydeen] step2 5단계: 기물 위치 부여 및 점수계산
  src/main/java/Board.java
  src/main/java/chess/Application.java
  src/main/java/chess/Board.java
  src/main/java/chess/LocationConverter.java
  src/main/java/chess/Rank.java
  src/main/java/pieces/Piece.java
  src/test/java/BoardTest.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PieceTest.java
Labels: Step2-5

#74 [JOHNNIE] 8단계: GUI나 웹으로 구현
  src/main/java/chess/ChessGame.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/config/ChessConfig.java
  src/main/java/chess/controller/ChessController.java
  src/main/java/chess/enums/Direction.java
  src/main/java/chess/enums/Type.java
  src/main/java/chess/game/Game.java
  src/main/java/chess/gui/ChessGameGUI.java
  src/main/java/chess/view/ChessView.java
  src/main/resources/pieces/white_pawn.png
  src/test/java/chess/game/GameTest.java
  src/test/java/chess/view/ViewTest.java
Labels: Step2-8

#73 [빙빙] step2 8단계: GUI나 웹으로 구현
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/chess/ChessApplication.java
  src/main/java/chess/game/Application.java
  src/main/java/chess/game/Board.java
  src/main/java/chess/game/ChessGame.java
  src/main/java/chess/game/ChessView.java
  src/main/java/chess/game/Direction.java
  src/main/java/chess/game/Position.java
  src/main/java/chess/game/Rank.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/main/java/chess/springchess/ChessConfig.java
  src/main/java/chess/springchess/ChessController.java
  src/main/java/chess/springchess/ChessConverter.java
  src/main/java/chess/springchess/ChessDto.java
  src/main/java/chess/springchess/Result.java
  src/main/java/chess/springchess/WebConfig.java
  src/main/resources/application.yml
  src/test/java/chess/GameTest.java
  src/test/java/chess/TestUtil.java
Labels: Step2-8

#75 [지토] step-5 기물 위치 부여 및 점수계산
  chess/.idea/encodings.xml
  chess/.idea/uiDesigner.xml
  chess/src/main/java/chess/Board.java
  chess/src/main/java/chess/Color.java
  chess/src/main/java/chess/Piece.java
  chess/src/main/java/chess/Position.java
  chess/src/main/java/chess/Rank.java
  chess/src/main/java/chess/Type.java
  chess/src/test/java/pieces/BoardTest.java
  chess/src/test/java/pieces/PawnTest.java
  chess/src/test/java/pieces/PieceTest.java
Labels: Step2-5

#77 [배찌] step6,7 체스 기물 이동 구현 및 예외처리
  app/src/main/java/App.java
  app/src/main/java/chess/App.java
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/ChessView.java
  app/src/main/java/chess/Game.java
  app/src/main/java/chess/Rank.java
  app/src/main/java/pieces/Bishop.java
  app/src/main/java/pieces/Blank.java
  app/src/main/java/pieces/Direction.java
  app/src/main/java/pieces/King.java
  app/src/main/java/pieces/Knight.java
  app/src/main/java/pieces/Pawn.java
  app/src/main/java/pieces/Piece.java
  app/src/main/java/pieces/Position.java
  app/src/main/java/pieces/Queen.java
  app/src/main/java/pieces/Rook.java
  app/src/main/java/pieces/Type.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/chess/ChessViewTest.java
  app/src/test/java/chess/GameTest.java
  app/src/test/java/pieces/PieceTest.java
  app/src/test/java/utils/StringUtilsTest.java
Labels: Step2-7

#76 [MUD] step-5 기물 위치 부여 및 점수계산
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/ChessGame.java
  app/src/main/java/chess/Position.java
  app/src/main/java/chess/Rank.java
  app/src/main/java/pieces/Piece.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/pieces/PieceTest.java
Labels: Step2-5

#78 [Glad] Step 2 - 8 GUI나 웹으로 구현
  .dockerignore
  Dockerfile
  app/build.gradle
  app/src/main/java/org/chess/App.java
  app/src/main/java/org/chess/config/WebConfig.java
  app/src/main/java/org/chess/domain/board/Board.java
  app/src/main/java/org/chess/domain/game/Game.java
  app/src/main/java/org/chess/domain/piece/impl/Pawn.java
  app/src/main/java/org/chess/web/ChessController.java
  app/src/main/java/org/chess/web/dto/MoveRequestDto.java
  app/src/main/java/org/chess/web/dto/MoveResultDto.java
  app/src/main/resources/application.properties
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/components/ChessGame.tsx
  frontend/src/main.tsx
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: Step2-8

#79 [BRIE] Step2-6,7 기물 이동 구현 및 예외 처리
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/ChessGame.java
  app/src/main/java/chess/Direction.java
  app/src/main/java/chess/Game.java
  app/src/main/java/chess/Position.java
  app/src/main/java/chess/Rank.java
  app/src/main/java/chess/ScoreCalculator.java
  app/src/main/java/pieces/Bishop.java
  app/src/main/java/pieces/Blank.java
  app/src/main/java/pieces/King.java
  app/src/main/java/pieces/Knight.java
  app/src/main/java/pieces/Pawn.java
  app/src/main/java/pieces/Piece.java
  app/src/main/java/pieces/PieceFactory.java
  app/src/main/java/pieces/Queen.java
  app/src/main/java/pieces/Rook.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/chess/GameTest.java
  app/src/test/java/chess/ScoreCalculatorTest.java
  app/src/test/java/pieces/BishopTest.java
  app/src/test/java/pieces/KingTest.java
  app/src/test/java/pieces/KnightTest.java
  app/src/test/java/pieces/PawnTest.java
  app/src/test/java/pieces/PieceTest.java
  app/src/test/java/pieces/QueenTest.java
  app/src/test/java/pieces/RookTest.java
Labels: Step2-7

#81 [Elbin] Step-5 5단계: 기물 위치 부여 및 점수계산
  .idea/encodings.xml
  .idea/misc.xml
  app/src/main/java/ChessGame.java
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/Position.java
  app/src/main/java/chess/Rank.java
  app/src/main/java/pieces/Piece.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/pieces/PieceTest.java
Labels: Step2-5
